max_sparsity: 26
min_sparsity: 5
sparsity_freq: 4
lambda_: 1e-1 # 1e-7 per T>=T60 # 1e-2 o 1e-3 per T50
lambda2: 0.2 # 0.5  per T>=T60 # 0.1 per T50
mu: 10 # 10 per T70
# beta: 0.9
# accelerateGD: False
max_iter: 1000 # 400 per T>= 50
max_iter_out: 100
max_iter_tot: 150
decouple_learning: False
topo_learning_mode: "optimistic"
tol: 1e-7
tol_out: 0.1 ################
patience: 10 # 5
verbose: True
QP: True
warmup: 2
on_test: False
complete: True
both: False
